from typing import TypedDict, Optional, List, Dict, Any


class AgentState(TypedDict):
    """
    Central state container passed between nodes in the LangGraph orchestration.
    
    Attributes:
        raw_requirement: Initial raw requirement input in plain text.
        process_definition: Structured process schema generated by the Analyst.
        design: Low-code specifications created by the Architect.
        review: Validation findings, pass/fail status, and targeted feedback.
        iteration: Current iteration index of the review-revision cycle.
        max_iterations: Configurable upper threshold before forcing pipeline termination.
        status: Execution status ('running', 'approved', 'max_iterations_reached', 'stalled_no_progress').
        log: Complete audit trail containing intermediate node responses for UI inspection.
        architect_stalled: Early exit flag set if the Architect fails to mutate design across revisions.
    """
    raw_requirement: str
    process_definition: Optional[Dict[str, Any]]
    design: Optional[Dict[str, Any]]
    review: Optional[Dict[str, Any]]
    iteration: int
    max_iterations: int
    status: str  # "running" | "approved" | "max_iterations_reached" | "stalled_no_progress"
    log: List[Dict[str, Any]]  # trace of every agent call, for the UI / live demo
    architect_stalled: bool  # True if the Architect's revision was identical to its previous design
